spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      generate-ddl: false
    show-sql: true